# Generated by Django 3.2.4 on 2021-07-01 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 1, 18, 13, 42, 333276, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
